services:
  frontend:
    expose:
      - "4173"
    image: shift-scheduler-frontend 
    build:
      context: ./frontend
    networks:
      shift-scheduler-net:
        ipv4_address: 10.5.0.4
    environment:
      - APP_API_URL=https://10.5.0.2:8443/api
  backend:
    networks:
      shift-scheduler-net:
        ipv4_address: 10.5.0.2
    expose:
      - "8443"
    image: shift-scheduler-backend 
    build:
      context: ./backend
    environment:
      - DB_IP=10.5.0.3
      - REDIS_HOST=10.5.0.5
      - LOAD_SAMPLE_DATA=true
  db:
    networks:
      shift-scheduler-net:
        ipv4_address: 10.5.0.3
    image: shift-scheduler-db
    build:
      context: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    networks:
      shift-scheduler-net:
        ipv4_address: 10.5.0.5
    image: redis
networks:
  shift-scheduler-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
